name: e_commerce
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.4.0
  provider: ^6.1.5
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  flutter_spinkit: ^5.2.1
  fluttertoast: ^8.2.12
  animations: ^2.0.11
  intl: ^0.20.2
  shimmer: ^3.0.0
  flutter_rating_bar: ^4.0.1
  carousel_slider: ^5.1.1
  badges: ^3.1.2
  dropdown_button2: ^2.3.9
  image_picker: ^1.1.2
  getwidget: ^6.0.0
  velocity_x: ^4.3.1
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/banners/banner1.png
    - assets/banners/banner2.png
    - assets/banners/banner3.png
    - assets/banners/banner4.png
    - assets/images/default_product.png
    - assets/demo_images/beeralu_lace_table_runner.png
    - assets/demo_images/coconut_shell_ladle_set.png
    - assets/demo_images/dumbara_mats.png
    - assets/demo_images/hand_carved_wooden_mask.png
    - assets/demo_images/traditional_clay_pot.png
    - assets/demo_images/wooden_elephant.png
    - assets/demo_images/kithul-honey.png
    - assets/demo_images/wood_rack.png
    - assets/demo_images/holder.png
    - assets/demo_images/garayaka.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/main.png"
